import { useState } from "react"

export const composeValue = <T>(first: T, second: T): T => {
    if (first !== undefined) {
        return first
    }
    return second
}

export const range = (n: number) => {
    const result: number[] = []
    for (let i = 0; i < n; i++) {
        result.push(i)
    }
    return result
}

const generateRandomId = (len: number) => {
    const byteToHex = (byte: number) => ('0' + byte.toString(16).slice(-2))
    const arr = new Uint8Array(len / 2)
    window.crypto.getRandomValues(arr)
    return Array.from(arr, byteToHex).join('')
}

export const useHtmlIdPrefix = (htmlIdPrefixProps?: string) => {
    if (htmlIdPrefixProps !== undefined) return htmlIdPrefixProps;
    const [autoGeneratedPrefix] = useState(() => `xform_${generateRandomId(6)}`)
    return autoGeneratedPrefix
}
